### ISSUE TITLE
[Bug] Can't toggle Dark Reader per-site

### ISSUE THREAD

**Issue by srnyx** [darkreader/darkreader#10611]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

I can't toggle Dark Reader per-site at all, and all sites have been changed to enable it by default. Meaning I'm stuck with Dark Reader enabled on **every** site unless I completely disable it.

### Website Address

All

### Steps To Reproduce

1. Install Dark Reader
2. Try to toggle for specific site

### Expected Behavior

It should successfully toggle on/off

### Actual Behavior

Nothing happens when you click on the website domain in the extension's menu.

### Operating System

Windows 11

### Web Browser name and version

Chrome 108.0.5359.125

### Dark Reader version

4.9.62

### Additional Context

This error is sent in dev console when menu is opened and when trying to view the `Site list`:
```
Uncaught (in promise) TypeError: props.values.map is not a function
    at TextList (index.js:3543:18)
    at ComponentVNode.unbox (index.js:649:27)
    at ComponentVNode.attach (index.js:681:34)
    at execute (index.js:395:19)
    at index.js:396:45
    at Array.forEach (<anonymous>)
    at execute (index.js:396:30)
    at index.js:396:45
    at Array.forEach (<anonymous>)
    at execute (index.js:396:30)
```

**Comment by srnyx** [comment]
Okay I should've tried updating Chrome before submitting the issue. After updating Chrome to `109.0.5414.75` (from `108.0.5359.125`), the extension works as intended. Sorry!
