### ISSUE TITLE
[Bug] Debug build is broken

### ISSUE THREAD

**Issue by iamkroot** [darkreader/darkreader#13077]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

Trying to build a fresh version of Dark Reader fails.

### Website Address

N/A

### Steps To Reproduce

1. clone the main branch
2. `npm install`
3. `npm run debug`

### Expected Behavior

Project builds

### Actual Behavior

```bash
❯ npm run debug

> darkreader@4.9.88 debug
> node --max-old-space-size=3072 tasks/cli.js build --debug

17:07:21 BUILD
17:07:21 clean (13ms)
17:07:21 bundle-html (6ms)
17:07:29 bundle-js error
RollupError: [plugin typescript] src/ui/popup/components/body.tsx (17:24): @rollup/plugin-typescript TS2307: Cannot find module '@plus/popup/plus-body' or its corresponding type declarations.
    at getRollupError (file:///home/kroot/Programming/gitclones/darkreader/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
    at error (file:///home/kroot/Programming/gitclones/darkreader/node_modules/rollup/dist/es/shared/parseAst.js:388:42)
    at Object.error (file:///home/kroot/Programming/gitclones/darkreader/node_modules/rollup/dist/es/shared/node-entry.js:19558:20)
    at emitDiagnostic (file:///home/kroot/Programming/gitclones/darkreader/node_modules/@rollup/plugin-typescript/dist/es/index.js:533:17)
    at reportDiagnostics (file:///home/kroot/Programming/gitclones/darkreader/node_modules/@rollup/plugin-typescript/dist/es/index.js:541:9)
    at Array.forEach (<anonymous>)
    at emitFilesAndReportErrors (/home/kroot/Programming/gitclones/darkreader/node_modules/typescript/lib/typescript.js:130463:15)
    at result.afterProgramCreate (/home/kroot/Programming/gitclones/darkreader/node_modules/typescript/lib/typescript.js:130646:5)
    at Object.afterProgramCreate (file:///home/kroot/Programming/gitclones/darkreader/node_modules/@rollup/plugin-typescript/dist/es/index.js:698:29)
    at synchronizeProgram (/home/kroot/Programming/gitclones/darkreader/node_modules/typescript/lib/typescript.js:130969:12)
Error [RollupError]: [plugin typescript] src/ui/popup/components/body.tsx (17:24): @rollup/plugin-typescript TS2307: Cannot find module '@plus/popup/plus-body' or its corresponding type declarations.
    at getRollupError (file:///home/kroot/Programming/gitclones/darkreader/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
    at error (file:///home/kroot/Programming/gitclones/darkreader/node_modules/rollup/dist/es/shared/parseAst.js:388:42)
    at Object.error (file:///home/kroot/Programming/gitclones/darkreader/node_modules/rollup/dist/es/shared/node-entry.js:19558:20)
    at emitDiagnostic (file:///home/kroot/Programming/gitclones/darkreader/node_modules/@rollup/plugin-typescript/dist/es/index.js:533:17)
    at reportDiagnostics (file:///home/kroot/Programming/gitclones/darkreader/node_modules/@rollup/plugin-typescript/dist/es/index.js:541:9)
    at Array.forEach (<anonymous>)
    at emitFilesAndReportErrors (/home/kroot/Programming/gitclones/darkreader/node_modules/typescript/lib/typescript.js:130463:15)
    at result.afterProgramCreate (/home/kroot/Programming/gitclones/darkreader/node_modules/typescript/lib/typescript.js:130646:5)
    at Object.afterProgramCreate (file:///home/kroot/Programming/gitclones/darkreader/node_modules/@rollup/plugin-typescript/dist/es/index.js:698:29)
    at synchronizeProgram (/home/kroot/Programming/gitclones/darkreader/node_modules/typescript/lib/typescript.js:130969:12) {
  pluginCode: 'TS2307',
  loc: {
    column: 24,
    line: 17,
    file: '/home/kroot/Programming/gitclones/darkreader/src/ui/popup/components/body.tsx'
  },
  frame: '\n' +
    "\x1B[7m17\x1B[0m import {PlusBody} from '@plus/popup/plus-body'; // eslint-disable-line\n" +
    '\x1B[7m  \x1B[0m \x1B[91m                       ~~~~~~~~~~~~~~~~~~~~~~~\x1B[0m\n',
  code: 'PLUGIN_ERROR',
  plugin: 'typescript',
  hook: 'buildStart',
  [Symbol(augmented)]: true
}
17:07:29 MISSION FAILED!
```

### Operating System

Linux

### Web Browser name and version

N/A

### Dark Reader version

main

### Additional Context

Might be related to https://github.com/darkreader/darkreader/commit/adbfd8dab8298a442c8ce827d663f9ba15e1f969

**Comment by sorpdev** [comment]
i get the same error when trying to build (windows)

**Comment by charrarr** [comment]
This seems to be caused by a number of references to a nonexistent src/plus/, which is defined as a symlink to a directory outside darkreader:
https://github.com/darkreader/darkreader/blob/0ad9872edf2609b288058c520667fa89dbbf745f/package.json#L18
I guess these changes are for an upcoming chrome build `chrome-plus` related to https://blog.chromium.org/2024/05/manifest-v2-phase-out-begins.html

**Comment by polyzen** [comment]
This was fixed in https://github.com/darkreader/darkreader/releases/tag/v4.9.89.1
