### ISSUE TITLE
[Broken Website] youtube.com Uncaught TypeError: Cannot read properties of undefined (reading 'get')

### ISSUE THREAD

**Issue by pavelsevcik** [darkreader/darkreader#13344]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Uncaught TypeError: Cannot read properties of undefined (reading 'get')
    at proxy.js:39:59
    at Array.forEach (<anonymous>)
    at overrideProperty (proxy.js:37:36)
    at proxy.js:365:17
    at Array.forEach (<anonymous>)
    at injectProxy (proxy.js:364:36)
    at injectProxyAndCleanup (proxy.js:492:9)
    at HTMLDocument.dataReceiver (proxy.js:516:9)
    
    
 

### Website Address

https://www.youtube.com/

### Steps To Reproduce

1. go to https://www.youtube.com/
2. open dev tools to see error

### Operating System

22.04.3-Ubuntu

### Web Browser name and version

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

### Dark Reader version

4.9.95

**Comment by alexanderby** [comment]
Does it happen to you all the time, or from time to time?

**Comment by pavelsevcik** [comment]
every time, here are the screenshots

youtube.com
![image](https://github.com/user-attachments/assets/1e4c7391-185f-4785-a966-4e230cd6745e)

youtu.com/watch
![image](https://github.com/user-attachments/assets/3454fc84-c84a-4e7d-8485-5b0472d22307)

as per instructions I did test it in browser with only Dark Reader
![image](https://github.com/user-attachments/assets/408cf885-2ce5-4f63-9330-3774e59f6779)

**Comment by alexanderby** [comment]
If you type the following lines in Console and press Enter, what do you see?
```javascript
Document.ptototype.adoptedStyleSheets;
```
```javascript
ShadowRoot.ptototype.adoptedStyleSheets;
```
```javascript
Object.getOwnPropertyDescriptor(Document.ptototype, 'adoptedStyleSheets');
```
```javascript
Object.getOwnPropertyDescriptor(Document.ptototype, 'ShadowRoot');
```

What do you get?

**Comment by pavelsevcik** [comment]
![image](https://github.com/user-attachments/assets/59c5aa61-eec1-4385-9a31-3ec6109e8711)

![image](https://github.com/user-attachments/assets/665d8faa-4ecb-4a56-a9bd-4e8477eaf1fc)

**Comment by alexanderby** [comment]
Sorry, my fault, could you please try `Object.getOwnPropertyDescriptor(ShadowRoot.prototype, 'adoptedStyleSheets')` and then for some another website?

**Comment by alexanderby** [comment]
I actually see they override the ShadowRoot with some weird 3rd party library, but for me that happens after Dark Reader's script injection. For you it happens before and it breaks our script. I will try to reproduce on Linux on Windows.

**Comment by pavelsevcik** [comment]
youtube.com

![image](https://github.com/user-attachments/assets/a2c32b3c-802d-4e73-a941-9ad1c52850fa)

google.com

![image](https://github.com/user-attachments/assets/62e25d2b-038c-4e83-9b60-e625324079b0)

**Comment by alexanderby** [comment]
Thank you, I will publish a patch soon.
