### ISSUE TITLE
[Bug] Replace with title

### ISSUE THREAD

**Issue by LesanuNicolas** [darkreader/darkreader#13645]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

I am using Angular v19. I put the darkreader on a slide-toggle from material. When I enable, I get this error: Uncaught ReferenceError: __spreadValues is not defined
    at overrideProperty (<anonymous>:28:33)
    at override (<anonymous>:37:11)
    at injectProxy (<anonymous>:85:9)
    at <anonymous>:316:9
    at createStaticStyleOverrides (darkreader.js:5961:21)
    at createThemeAndWatchForUpdates (darkreader.js:6166:5)
    at success (darkreader.js:6376:9)
    at ready (darkreader.js:6389:9)
    at createOrUpdateDynamicThemeInternal (darkreader.js:6393:7)
    at enable (darkreader.js:6692:5). 
    Also when I press enable, the browser freezes a bit until it enters in dark mode(along with that click message down below). I made sure the error + the freeze comes from darkreader.
    This is the code responsible for toggle/untoggle: 
      private _updateDarkMode(isEnabled: boolean): void {
    if (!isEnabled) {
      disableDarkMode();
      return;
    }

    enableDarkMode({
      brightness: 100,
      contrast: 100,
      sepia: 0
    });
  }
  if I comment it, the browser no longer freezes, I am almost sure it might be from the enableDarkMode method.
  I can show you anything you want: tsconfig, dependencies.. I use tslib 2.6.2 and ES2022:   "target": "ES2022",
    "module": "ES2022",
   

### Website Address

localhost

### Steps To Reproduce

Enable dark mode.

### Expected Behavior

Was expecting a smooth experience without errors

### Actual Behavior

I have an error and browser freezes when I enable

### Screenshots

![image](https://github.com/user-attachments/assets/eee5dfa8-70c2-4b94-b6aa-4baafe219f52)

### Operating System

Windows

### Web Browser name and version

Vivaldi

### Dark Reader version

4.9.96

**Comment by bwaxler** [comment]
Getting the same exact error with Angular 19. It doesn't seem to affect much as all the darkreader styles are still applied, etc.

As for the freeze you mention, I do get a slight pause but its less than a second and I assume its simply darkreader creating the CSS.

**Comment by Venom1991** [comment]
The only thing that helped was patching this missing function within the main.ts file (before everything else):

```
// Patch for missing __spreadValues helper (used by DarkReader ESM bundle)
(window as any).__spreadValues = (first: any, second: any) => {
  for (const prop in second) {
    if (Object.prototype.hasOwnProperty.call(second, prop)) {
      first[prop] = second[prop];
    }
  }

  return first;
};
```

No more errors.

**Comment by dwilches** [comment]
The workaround above doesn't work when `optimization=true` in `angular.json` because of the name mangling:

```
Uncaught ReferenceError: Qe is not defined
    at le (<anonymous>:1:525)
    at Se (<anonymous>:1:724)
    at WA (<anonymous>:1:1421)
    at <anonymous>:1:5125
    at LO (darkreader.js:5962:21)
    at V (darkreader.js:6167:5)
    at X (darkreader.js:6377:9)
    at z (darkreader.js:6390:9)
    at NZ (darkreader.js:6394:7)
    at KP (darkreader.js:6693:5)
    at r.enableDarkMode (dark-mode.service.ts:51:13)
    at new r (dark-mode.service.ts:19:14)
    at Wz.ɵfac [as factory] (dark-mode.service.ts:65:5)
    at ho.hydrate (core.mjs:2251:33)
    at ho.get (core.mjs:2125:23)
```

`__spreadValues` gets obfuscated as `Qe`, thus failing to find the function by the original name. This line in DarkReader:

    const newDescriptor = {...oldDescriptor};

Becomes:

    let _i = Qe({}, Qa);

Where `Qe` was originally `__spreadValues`.
