### ISSUE TITLE
hanime.tv fails to initialize when DarkReader is open

### ISSUE THREAD

**Issue by ImChinaNB** [darkreader/darkreader#1605]
When I opened https://hanime.tv/ with DarkReader on, the website loaded but when I clicked on [Sign In] button, nothing happened. I opened the developer tool and found that Vue.js caused an error:
```javascript
vue.runtime.min.js:6 TypeError: n.setAttribute is not a function
    at Array.ar (vue.runtime.min.js:6)
    at x (vue.runtime.min.js:6)
    at i.__patch__ (vue.runtime.min.js:6)
    at i._update (vue.runtime.min.js:6)
    at i.o (vue.runtime.min.js:6)
    at ke.get (vue.runtime.min.js:6)
    at ke.run (vue.runtime.min.js:6)
    at xe (vue.runtime.min.js:6)
    at Array.<anonymous> (vue.runtime.min.js:6)
    at zt (vue.runtime.min.js:6)
Rt @ vue.runtime.min.js:6
Ft @ vue.runtime.min.js:6
Mt @ vue.runtime.min.js:6
(anonymous) @ vue.runtime.min.js:6
zt @ vue.runtime.min.js:6
Promise.then (async)
Ut @ vue.runtime.min.js:6
Gt @ vue.runtime.min.js:6
(anonymous) @ vue.runtime.min.js:6
ke.update @ vue.runtime.min.js:6
ot.notify @ vue.runtime.min.js:6
set @ vue.runtime.min.js:6
(anonymous) @ vue.runtime.min.js:6
It @ vue.runtime.min.js:6
t.extend @ vue.runtime.min.js:6
Ye @ vue.runtime.min.js:6
(anonymous) @ vue.runtime.min.js:6
nn @ vue.runtime.min.js:6
o._c @ vue.runtime.min.js:6
(anonymous) @ d395ade7bed751cfb080.js:1
Ne @ vue.runtime.min.js:6
(anonymous) @ d395ade7bed751cfb080.js:1
ln._render @ vue.runtime.min.js:6
o @ vue.runtime.min.js:6
ke.get @ vue.runtime.min.js:6
ke @ vue.runtime.min.js:6
vn.$mount @ vue.runtime.min.js:6
init @ vue.runtime.min.js:6
k @ vue.runtime.min.js:6
k @ vue.runtime.min.js:6
k @ vue.runtime.min.js:6
(anonymous) @ vue.runtime.min.js:6
_update @ vue.runtime.min.js:6
o @ vue.runtime.min.js:6
ke.get @ vue.runtime.min.js:6
ke @ vue.runtime.min.js:6
vn.$mount @ vue.runtime.min.js:6
init @ vue.runtime.min.js:6
k @ vue.runtime.min.js:6
(anonymous) @ vue.runtime.min.js:6
_update @ vue.runtime.min.js:6
o @ vue.runtime.min.js:6
ke.get @ vue.runtime.min.js:6
ke @ vue.runtime.min.js:6
vn.$mount @ vue.runtime.min.js:6
init @ vue.runtime.min.js:6
k @ vue.runtime.min.js:6
k @ vue.runtime.min.js:6
(anonymous) @ vue.runtime.min.js:6
_update @ vue.runtime.min.js:6
o @ vue.runtime.min.js:6
ke.get @ vue.runtime.min.js:6
ke @ vue.runtime.min.js:6
vn.$mount @ vue.runtime.min.js:6
init @ vue.runtime.min.js:6
k @ vue.runtime.min.js:6
k @ vue.runtime.min.js:6
(anonymous) @ vue.runtime.min.js:6
_update @ vue.runtime.min.js:6
o @ vue.runtime.min.js:6
ke.get @ vue.runtime.min.js:6
ke @ vue.runtime.min.js:6
vn.$mount @ vue.runtime.min.js:6
r @ d395ade7bed751cfb080.js:1
(anonymous) @ d395ade7bed751cfb080.js:1
tryCatch @ polyfill.min.js:3
invoke @ polyfill.min.js:3
t.<computed> @ polyfill.min.js:3
r @ 6c4aabe464affc9da480.js:1
c @ 6c4aabe464affc9da480.js:1
Promise.then (async)
r @ 6c4aabe464affc9da480.js:1
c @ 6c4aabe464affc9da480.js:1
Promise.then (async)
r @ 6c4aabe464affc9da480.js:1
c @ 6c4aabe464affc9da480.js:1
(anonymous) @ 6c4aabe464affc9da480.js:1
(anonymous) @ 6c4aabe464affc9da480.js:1
ge @ d395ade7bed751cfb080.js:1
(anonymous) @ d395ade7bed751cfb080.js:1
Promise.then (async)
161 @ d395ade7bed751cfb080.js:1
n @ ce3eeabf673262708887.js:1
117 @ d395ade7bed751cfb080.js:1
n @ ce3eeabf673262708887.js:1
f @ ce3eeabf673262708887.js:1
a @ ce3eeabf673262708887.js:1
(anonymous) @ d395ade7bed751cfb080.js:1
Show 39 more frames
d395ade7bed751cfb080.js:1 [nuxt] Error while initializing app DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://cdn.jsdelivr.net/npm/vue@2.5.17/dist/vue.runtime.min.js:6:37746)
    at l (https://cdn.jsdelivr.net/npm/vue@2.5.17/dist/vue.runtime.min.js:6:49782)
    at b (https://cdn.jsdelivr.net/npm/vue@2.5.17/dist/vue.runtime.min.js:6:49523)
    at v (https://cdn.jsdelivr.net/npm/vue@2.5.17/dist/vue.runtime.min.js:6:49865)
    at k (https://cdn.jsdelivr.net/npm/vue@2.5.17/dist/vue.runtime.min.js:6:53142)
    at i.__patch__ (https://cdn.jsdelivr.net/npm/vue@2.5.17/dist/vue.runtime.min.js:6:53498)
    at i._update (https://cdn.jsdelivr.net/npm/vue@2.5.17/dist/vue.runtime.min.js:6:31681)
    at i.o (https://cdn.jsdelivr.net/npm/vue@2.5.17/dist/vue.runtime.min.js:6:60796)
    at ke.get (https://cdn.jsdelivr.net/npm/vue@2.5.17/dist/vue.runtime.min.js:6:15996)
    at new ke (https://cdn.jsdelivr.net/npm/vue@2.5.17/dist/vue.runtime.min.js:6:15914)
```
However, after I turned off the DarkReader and refreshed the page, it worked normally.
Reproduced for a few times, with Chrome and Firefox (only DarkReader installed).

**Comment by brazenvoid** [comment]
@hanghang0702 Thanks for making this an issue! Fortunately I stumbled on it through Google by searching the very same vue error...

I had started using Chrome (with no dark reader) for the site, thinking they finally made a breaking change for Firefox as they don't support it officially.

**Comment by Gusted** [comment]
Resolved.
