### ISSUE TITLE
Build from 85b479a fails Inversion Fixes config test

### ISSUE THREAD

**Issue by marcelpaulo** [darkreader/darkreader#385]
Earlier today I built darkreader from 94bf57a0c8a2cf731daa380933fb545aa0ea1505 like this:

```
git clone https://github.com/darkreader/darkreader
cd darkreader
npm install
npm run release
```

Some moments ago, I noticed there 2 new commits after 94bf57a0c8a2cf731daa380933fb545aa0ea1505, so I tried to update:

```
git pull
npm install
npm run release
```

but the build failed at the `Inversion Fixes config` test. Here's the build log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'release' ]
2 info using npm@5.6.0
3 info using node@v9.11.1
4 verbose run-script [ 'prerelease', 'release', 'postrelease' ]
5 info lifecycle darkreader@4.2.5~prerelease: darkreader@4.2.5
6 info lifecycle darkreader@4.2.5~release: darkreader@4.2.5
7 verbose lifecycle darkreader@4.2.5~release: unsafe-perm in lifecycle true
8 verbose lifecycle darkreader@4.2.5~release: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/paulo/src/darkreader/node_modules/.bin:/home/paulo/stage/bin:/home/paulo/bin:/home/paulo/.local/bin:/home/paulo/.cabal/bin:/home/paulo/.cargo/bin:/home/paulo/go/bin:/usr/local/go/bin:/home/paulo/stage/bin:/home/paulo/bin:/home/paulo/.local/bin:/home/paulo/.cabal/bin:/home/paulo/.cargo/bin:/home/paulo/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
9 verbose lifecycle darkreader@4.2.5~release: CWD: /home/paulo/src/darkreader
10 silly lifecycle darkreader@4.2.5~release: Args: [ '-c', 'npm test && gulp release' ]
11 silly lifecycle darkreader@4.2.5~release: Returned: code: 1  signal: null
12 info lifecycle darkreader@4.2.5~release: Failed to exec release script
13 verbose stack Error: darkreader@4.2.5 release: `npm test && gulp release`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid darkreader@4.2.5
15 verbose cwd /home/paulo/src/darkreader
16 verbose Linux 4.13.0-38-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "release"
18 verbose node v9.11.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error darkreader@4.2.5 release: `npm test && gulp release`
22 error Exit status 1
23 error Failed at the darkreader@4.2.5 release script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I pasted all build output [here](https://pastebin.com/3k9q8jDZ)

I'm running **nodejs 9.11.1** on **Xubuntu 17.10**. Please let me know how I can help debug this further.

**Comment by marcelpaulo** [comment]
I've just tested: the build is OK from f56bcc157dd6a075c890cf3cad1d4e4266482e36, so the issue seems to have been introduced by 85b479aa81d8c9dae28cc5cbe16f9acde4c4d082.

**Comment by alexanderby** [comment]
I've moved the repository some days ago and seems like Travis CI stopped working.

**Comment by marcelpaulo** [comment]
Wow, that was speed-lightning fast ! Thanks, @alexanderby ! I've just built from c20053eb7329f051161b9b5959622774305badb9 and the issue is gone.

By the way, congratulations for this remarkable extension, it works wonderfully ! Not only that, it's exceedingly flexible and easy to configure. I'm happy I stumbled across it.
