### ISSUE TITLE
[BUG] npm run error: Cannot read property 'numerator' of undefined

### ISSUE THREAD

**Issue by elig0n** [darkreader/darkreader#4584]
After running `npm install`, then either `npm run debug` or `npm run build` fails with:
```
bundle-css error
TypeError: Cannot read property 'numerator' of undefined
    at Dimension.operate (.../darkreader-master/node_modules/less/src/less/tree/dimension.js:77:35)
    at Operation.eval (.../darkreader-master/node_modules/less/src/less/tree/operation.js:40:22)
    at Expression.eval (.../darkreader-master/node_modules/less/src/less/tree/expression.js:43:41)
    at Value.eval (.../darkreader-master/node_modules/less/src/less/tree/value.js:26:34)
    at Declaration.eval (.../darkreader-master/node_modules/less/src/less/tree/declaration.js:67:37)
    at Ruleset.eval (.../darkreader-master/node_modules/less/src/less/tree/ruleset.js:191:54)
    at Ruleset.eval (.../darkreader-master/node_modules/less/src/less/tree/ruleset.js:191:54)
    at Ruleset.eval (.../darkreader-master/node_modules/less/src/less/tree/ruleset.js:191:54)
    at Object.default_1 [as default] (.../darkreader-master/node_modules/less/src/less/transform-tree.js:80:22)
    at ParseTree.toCSS (.../darkreader-master/node_modules/less/src/less/parse-tree.js:17:42)
```
Tested with `npm` of node LTS versions: 
node-v12.20.0-linux-x64
node-v14.15.3-linux-x64

**Comment by Gusted** [comment]
Aha, so I was not the only one. I tought it was some regression and included a fix in a PR https://github.com/darkreader/darkreader/pull/3519/commits/bcf5501b158600c5ebb883ffab3e43b6f1619c16#diff-436e9ed240ba4fb8b60a3e5c81952c2e7edf2ac2d05f17133e270ba00d148461R20 However seems to be on master branch as well. Give me a minute to merge the fix.
