### ISSUE TITLE
[Bug] Can't disable Dark Reader on github.com, also can't access the site list or manage settings at all, both blank

### ISSUE THREAD

**Issue by LoganDark** [darkreader/darkreader#7402]
# Bug Report

## Bug Description
Dark Reader seems to have gained a mind of its own. It won't let me disable it on github.com, and it's completely rejecting any attempts to access the site list or settings in any way.

I don't know what to do as I can't access anything I would need to debug this. It's all completely blank.

## Screenshots
https://user-images.githubusercontent.com/4723091/142128925-7d293df1-ad2a-4f79-b9dd-0d78e5ebf13f.mp4

## System Information
- OS: Windows 10 OS Version 2004 (Build 19041.928)
- Browser: Google Chrome 91.0.4472.101 (Official Build) (64-bit) (cohort: Stable)
- Dark Reader Version: 4.9.42

## Additional Context
N/A

**Comment by LoganDark** [comment]
Oh, here is something - an error that happens whenever I try to disable Dark Reader for this site:

```
Error in event handler: TypeError: this.user.settings.siteList.slice is not a function
    at Extension.toggleURL (chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/background/index.js:5059:47)
    at Object.toggleURL (chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/background/index.js:4854:42)
    at Messenger.onUIMessage (chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/background/index.js:2738:34)
    at chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/background/index.js:2638:30
```

Disabling it globally works, but is not very fun on other sites.

No errors when trying to access the site list or manage settings.

**Comment by LoganDark** [comment]
![image](https://user-images.githubusercontent.com/4723091/142129791-3bad18a5-3c18-40fe-95fe-17a10e95c477.png)

Why is siteList an object and not an array? It looks like all of my site settings have been completely overwritten with this somehow.

**Comment by LoganDark** [comment]
Setting `this.user.settings.siteList` to `[]` manually (by storing `this.user` in a global variable and doing `temp1.siteList = []`) fixes the issue. I'm not sure how `siteList` got replaced, though. That's probably the root cause here.

**Comment by Gusted** [comment]
Hi @LoganDark!

That's a weird issue, the splitting code work should work(otherwise it should give you a error in the background-script about why it failed).



> (also, I have sync turned off)

This concerns me, as the only time that specific code can be executed is when you have sync enabled as the splitting code is embedded with the saving to the sync storage.

**Comment by LoganDark** [comment]
> the splitting code work should work

This time it didn't :(

> the only time that specific code can be executed is when you have sync enabled as the splitting code is embedded with the saving to the sync storage

Well, it seems like it was executed at the wrong time then, somehow.

**Comment by Gusted** [comment]
> Well, it seems like it was executed at the wrong time then, somehow.

That's a bit of the problem, it cannot executed wrong. Unless you mysteriously got hit by a chromium bug of executing javascript.

The code that transforms it into splitting is a new variable that is only accessible and used of the sync writing function.

**Comment by LoganDark** [comment]
> The code that transforms it into splitting is a new variable that is only accessible and used of the sync writing function.

Why does it operate directly on `this.user.settings`?

**Comment by Gusted** [comment]
> Why does it operate directly on `this.user.settings`?

It doesn't, which is the whole "joke". The spllited settings are saved into `chrome.storage.sync` and thus can only be received after a browser restart whereby `syncSettings` is true and thus the settings will be get by `chrome.storage.sync` that's the only possible path whereby you should get such meta_split_county/

**Comment by LoganDark** [comment]
But I didn't restart Chrome in between when it was working and when it stopped working. In fact, I haven't restarted Chrome in nearly a month

**Comment by Gusted** [comment]
> But I didn't restart Chrome in between when it was working and when it stopped working. In fact, I haven't restarted Chrome in nearly a month

That's even more concerning, but I do know that chrome does restart chromes between sleeps of a computer to save up memory.

**Comment by LoganDark** [comment]
> > But I didn't restart Chrome in between when it was working and when it stopped working. In fact, I haven't restarted Chrome in nearly a month
> 
> That's even more concerning, but I do know that chrome does restart chromes between sleeps of a computer to save up memory.

My computer doesn't sleep either, even overnight :)

**Comment by Gusted** [comment]
> Have any theories about how this could have happened

Well - I don't have any other then that you've possibly hitted a bug with chrome which might be due to having it open for so long.

**Comment by LoganDark** [comment]
So Chrome just starts randomly calling functions then? xD

**Comment by Gusted** [comment]
> So Chrome just starts randomly calling functions then? xD

I really don't have a clue. It just logically cannot happen, I've tried to reproduce the issue myself but each time it just managed like fine as it has to behave.

**Comment by RomanKornev** [comment]
Was having the same exact issue myself. It started about a month ago. 
My `000003.log` file contained something like this:
```
siteList{"__meta_split_count":2}siteListEnabled["site.com"]
siteList_0�F"[\"site1.com\",\"site2.com\",\"site3.com\"...all the other sites...
siteList_1"om\"]"syncSettingstruesyncSitesFixesfalsetheme�{"brightness":100,"contrast":100,"darkColorScheme":"Default","darkSchemeBackgroundColor...
```
Deleted my `Local Extension Settings/eimadpbcbfnmbkopoojfekhnkhdbieeh` and it's back to normal, even all my previous settings are back.
Very strange.

**Comment by CyberStrike** [comment]
Had the same issue on OSX Chrome 97.0.4692.71 it started a few hours ago. Uninstall and Reinstall of Extension has fixed it at the moment.

```
Error in event handler: TypeError: this.user.settings.siteList.slice is not a function
    at Extension.toggleURL (chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/background/index.js:5060:47)
    at Object.toggleURL (chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/background/index.js:4855:42)
    at Messenger.onUIMessage (chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/background/index.js:2739:34)
    at chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/background/index.js:2639:30
```

**Comment by Gusted** [comment]
> Had the same issue on OSX Chrome 97.0.4692.71 it started a few hours ago. Uninstall and Reinstall of Extension has fixed it at the moment.
> 
> ```
> Error in event handler: TypeError: this.user.settings.siteList.slice is not a function
>     at Extension.toggleURL (chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/background/index.js:5060:47)
>     at Object.toggleURL (chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/background/index.js:4855:42)
>     at Messenger.onUIMessage (chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/background/index.js:2739:34)
>     at chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/background/index.js:2639:30
> ```

Seems like another issue. Please open a separate issue for that.
