### ISSUE TITLE
[Bug] Site Toggle, Site List, & More Tabs Broken

### ISSUE THREAD

**Issue by techiata** [darkreader/darkreader#8467]
# Bug Report

## Website Address
Example Site Used for screenshots/screen recordings: https://github.com/darkreader/darkreader/
Issue applies to All Sites though

## Bug Description

When using the Site Toggle shortcut key combo, or clicking on the Dark Reader Extension icon and then the site name, the site doesn't change from dark to light mode or vice versa. The Site list page also only displays "Invert Listed Only" and  "Not Invert Listed" table headers with no cells bellow them. The More tab is also blank. Disabling and re-enabling the extension, restarting Chrome, or using Incognito Mode doesn't fix the issue. I've had this issue happen once before and after clearing out all the extensions data files (local and synced) and then reinstalling the extension, the issue is fixed, but I lose my configured site list.  This issue just came back again after about a week of no issues. I checked the Console log before I cleared the extension data last time (but didn't copy the error down) and noticed an error that I believe is similar to the error I'm seeing now:

```
Uncaught (in promise) TypeError: props.values.map is not a function
    at TextList (index.js:3417:18)
    at ComponentVNode.unbox (index.js:649:27)
    at ComponentVNode.attach (index.js:681:34)
    at execute (index.js:395:19)
    at index.js:396:45
    at Array.forEach (<anonymous>)
    at execute (index.js:396:30)
    at index.js:396:45
    at Array.forEach (<anonymous>)
    at execute (index.js:396:30)
```

    
    
The last time this issue happened, it spread (site list is being synced between clients using my same signed in Google account Chrome profile) and affected my work Macbook (Chrome) and also my 2 personal Windows 10 Computers (Chrome). Currently as i'm writing this, the issue is only on my Mac Chrome browser, but could spread to my Windows computer after the next time Chrome decides to sync its extension data.

This issue may be similar to Bug #8439, but on macOS at least, local .html and .pdf files are protected and can't be modified by Dark Reader, so i couldn't reproduce the issue on my machine in a new Chrome profile.

## Steps To Reproduce

1. Start with a fresh install of Dark Reader
2. Use the extension for X period of time, accessing various sites/files and adding various sites to local site list
3. ???
4. Extension breaks until i clear the extension data
5. Repeat

## Expected Behavior

Dark Reader works as normal, allowing me to toggle individual sites between dark and light mode
## Actual Behavior

Dark Reader randomly stops working until extension data is cleared out, losing personal site list
## Screenshots

![Screen Shot 2022-03-17 at 6 39 19 PM](https://user-images.githubusercontent.com/15114947/158921204-8ec71549-1ce1-4f29-8243-76e6808c3446.png)
![Screen Shot 2022-03-17 at 6 39 25 PM](https://user-images.githubusercontent.com/15114947/158921212-d284055f-af9a-4bc0-b9c7-c7d9410a3162.png)
![Screen Shot 2022-03-17 at 6 39 30 PM](https://user-images.githubusercontent.com/15114947/158921216-630c08fc-03dc-480f-be5e-07504e8591bb.png)
https://user-images.githubusercontent.com/15114947/158921274-5ed3f40d-562c-4592-ae78-ed5c61affa41.mov

## System Information

- OS: macOS & Windows 
- Browser: Chrome 99.0.4844.74 (Mac) Chrome 99 (Windows) 
- Dark Reader Version: 4.9.47 

## Additional Context

- Dark Reader was installed directly from Chrome Web Store and was the official extension.
- You may notice I have uBlock Origin installed also, disabling uBlock Origin doesn't change anything when Dark Reader is in a broken state.
- I'm leaving Dark Reader broken on my Mac (and likely to soon be broken on my Windows computers as well) so further troubleshooting can be done.
- This is my first Github bug on a public project, I tried to be as thorough as possible with my bug report, but please let me know if there is any additional info I should add, or formatting tips for future bug reports. Thanks!

**Comment by techiata** [comment]
I tried clicking on some of the file links in the Console log, but my coding/code reading skills are very basic. My thinking is when I add a certain site/URI type to my personal Dark Reader Site list and then the function that parses that list reads that site/URI type and a good chunk of the extension breaks as a result.

**Comment by Gusted** [comment]
Hmm weird, it seems like your siteList has a saved into a format which isn't a string... Would be interested to know which type it is instead.

So.
1. `chrome://extensions/`
2. Right-top Enable developer mode.
3. Click on `Inspect view LINK_HERE`(at the dark reader info card) and then on the LINK_HERE part.
4. Go to console tab.

Do so see any errors there?
If none.
5. Post the expanded output(redacted if needed) of `chrome.storage.local.get(null, console.log)` & `chrome.storage.sync.get(null, console.log)`.

**Comment by techiata** [comment]
Performed Steps 1-4 and here is the Console output:

```
Welcome to Dark Reader!
index.html:1 Unchecked runtime.lastError: The tab was closed.
ssl.gstatic.com/gb/images/a/71060be5b3.png:1          Failed to load resource: the server responded with a status of 404 ()
ssl.gstatic.com/gb/images/a/e2c0b463b4.png:1          Failed to load resource: the server responded with a status of 404 ()
ssl.gstatic.com/gb/images/a/71060be5b3.png:1          Failed to load resource: the server responded with a status of 404 ()
ssl.gstatic.com/gb/images/a/e2c0b463b4.png:1          Failed to load resource: the server responded with a status of 404 ()
ajax.googleapis.com/ajax/libs/angular_material/1.1.9/angular-material.min.css:1          Failed to load resource: net::ERR_NAME_NOT_RESOLVED
www.gstatic.com/_/voice/_/ss/k=voice.voice_module_set.BjcCs7po51I.L.W.O/am=BA/d=0/rs=AJAOlGnog_gpIgIvDYoTeC7RH1apPd-52Q:1          Failed to load resource: net::ERR_NAME_NOT_RESOLVED
ssl.gstatic.com/gb/images/a/71060be5b3.png:1          Failed to load resource: the server responded with a status of 404 ()
ssl.gstatic.com/gb/images/a/e2c0b463b4.png:1          Failed to load resource: the server responded with a status of 404 ()
www.gstatic.com/billing-ui/images/activityindicator/quantum_spinner_multicolored_87px_ae39165462d434417c9d93122bc4315c.gif:1          Failed to load resource: net::ERR_NAME_NOT_RESOLVED
28index.js:5124 Uncaught (in promise) TypeError: sourceList.slice is not a function
    at getToggledList (index.js:5124:41)
    at Extension.toggleActiveTab (index.js:5146:33)
darkreader.github.io/blog/posts.json:1          Failed to load resource: net::ERR_NAME_NOT_RESOLVED
index.js:3255 TypeError: Failed to fetch
    at Newsmaker.getNews (index.js:3236:40)
    at Newsmaker.updateNews (index.js:3216:37)
    at Newsmaker.alarmListener (index.js:3181:26)
    at index.js:3205:22
getNews @ index.js:3255
darkreader.github.io/blog/posts.json:1          Failed to load resource: net::ERR_NAME_NOT_RESOLVED
index.js:3255 TypeError: Failed to fetch
    at Newsmaker.getNews (index.js:3236:40)
    at Newsmaker.updateNews (index.js:3216:37)
    at Newsmaker.alarmListener (index.js:3181:26)
    at index.js:3205:22
getNews @ index.js:3255
darkreader.github.io/blog/posts.json:1          Failed to load resource: net::ERR_NAME_NOT_RESOLVED
index.js:3255 TypeError: Failed to fetch
    at Newsmaker.getNews (index.js:3236:40)
    at Newsmaker.updateNews (index.js:3216:37)
    at Newsmaker.alarmListener (index.js:3181:26)
    at index.js:3205:22
getNews @ index.js:3255
6index.js:5124 Uncaught (in promise) TypeError: sourceList.slice is not a function
    at getToggledList (index.js:5124:41)
    at Extension.toggleActiveTab (index.js:5146:33)
```

    
Also, Step 5 Output:
    
chrome.storage.local.get(null, console.log):

```
chrome.storage.local.get(null, console.log)
undefined
{applyToListedOnly: true, automation: '', automationBehaviour: 'OnOff', changeBrowserTheme: false, customThemes: Array(0), …}
applyToListedOnly: true
automation: ""
automationBehaviour: "OnOff"
changeBrowserTheme: false
customThemes: []
detectDarkTheme: false
dev_dynamic_theme_fixes: null
dev_inversion_fixes: null
dev_static_themes: null
enableContextMenus: false
enableForPDF: false
enableForProtectedPages: false
enabled: true
fetchNews: true
location: {latitude: null, longitude: null}
notifyOfNews: false
presets: []
previewNewDesign: false
readNews: (15) ['2m-users', 'automation', 'product-hunt-golden-kitty-2018', 'time-settings', 'safari', '500k-users', 'stylish', 'product-hunt', 'custom-site-settings', 'thanks-for-contribution', 'dynamic-theme', 'attention', 'dr-5-announcement', 'v4-9-16', 'v4-9']
siteList: {__meta_split_count: 2}
siteListEnabled: []
siteList_0: "[\"cloud.google.com\",\"www.newpower99.com\",\"batterykings.com\",\"www.good-win-racing.com\",\"surveys.google.com\",\"www.theverge.com\",\"www.asus-accessories.com\",\"bugs.chromium.org\",\"regexr.com\",\"fab9tuning.com\",\"pcpartpicker.com\",\"www.newegg.com\",\"www.fastforwardsuperchargers.com\",\"unraid.net\",\"www.reddit.com\",\"www.escapefromtarkov.com\",\"secure.reliantparking.com\",\"www.amd.com\",\"www.gamestop.com\",\"switchchargers.com\",\"propertysales.geico.com\",\"service.geico.com\",\"drop.com\",\"www.paypal.com\",\"www.kickstarter.com\",\"www.ups.com\",\"www.southwest.com\",\"shop.americantourister.com\",\"www.keychron.com\",\"gsuite.google.com\",\"domains.google\",\"blog.briancmoses.com\",\"www.fueleconomy.gov\",\"chromium-review.googlesource.com\",\"www.ea.com\",\"telegram.org\",\"www.makeuseof.com\",\"www.androidcentral.com\",\"manage.autodesk.com\",\"www.autodesk.com\",\"knowledge.autodesk.com\",\"www.indiegogo.com\",\"jenkins.io\",\"openhomelab.org\",\"demo.portainer.io\",\"tickets.oculusvr.com\",\"shopping.google.com\",\"forum.miata.net\",\"ghost.org\",\"play.date\",\"www.zunsport.com\",\"garagestar.com\",\"www.topmiata.com\",\"www.winamp.com\",\"www.canakit.com\",\"www.newark.com\",\"www.zillow.com\",\"www.protocol.com\",\"downforeveryoneorjustme.com\",\"fi.google.com\",\"www.bestbuy.com\",\"www.wlkata.com\",\"www.shapeways.com\",\"icr-am.asus.com\",\"bringatrailer.com\",\"zoom.us\",\"www.dailymotion.com\",\"app.shopmonkey.io\",\"www.fedex.com\",\"na.playtesting.ea.com\",\"192.168.1.1\",\"app.diagrams.net\",\"www.bizcom-us.com\",\"moonlight-stream.org\",\"parsecgaming.com\",\"www.yahoo.com\",\"www.instagram.com\",\"www.freedompop.com\",\"forum.dd-wrt.com\",\"tomato.groov.pl\",\"www.myopenrouter.com\",\"www.loopnet.com\",\"developers.google.com\",\"10.0.0.1\",\"www.tunemymusic.com\",\"www.asus.com\",\"www.eurodk.com\",\"finance.yahoo.com\",\"www.sonnetstore.com\",\"www.server-racks.com\",\"developer.chrome.com\",\"www.youtube.com\",\"helpx.adobe.com\",\"owncloud.online\",\"signin.ea.com\",\"groups.google.com\",\"www.laptoparena.net\",\"www.discounttiredirect.com\",\"advantiwheel.com\",\"www.americastire.com\",\"www.bing.com\",\"us.puma.com\",\"www.home-assistant.io\",\"howtune.com\",\"www.samsung.com\",\"xcp-ng.org\",\"www.proxmox.com\",\"ubuntu.com\",\"chromeos-cookbooks.firebaseapp.com\",\"www.clipular.com\",\"www.ebay.com\",\"noctua.at\",\"www.realvnc.com\",\"www.nomachine.com\",\"www.udemy.com\",\"www.homedepot.com\",\"www.cvs.com\",\"www.apple.com\",\"wiiu.hacks.guide\",\"www.linkedin.com\",\"store.nintendo.com\",\"en-americas-support.nintendo.com\",\"learnxinyminutes.com\",\"www.apartments.com\",\"eaca.co1.qualtrics.com\",\"store.google.com\",\"www.otterbox.com\",\"cricut.com\",\"www.oculus.com\",\"www.walmart.com\",\"play.google.com\",\"peach.blender.org\",\"chromium.googlesource.com\",\"www.toyotires.com\",\"keep.google.com\",\"www.cargurus.com\",\"www.logitech.com\",\"www.mazdausa.com\",\"www.needtags.com\",\"wwwapps.ups.com\",\"www.icloud.com\",\"appleid.apple.com\",\"docs.google.com\",\"myaccount.ea.com\",\"pay.google.com\",\"deltaemulator.com\",\"cutdl.xyz\",\"www.dyson.com\",\"www.target.com\",\"buy.logitech.com\",\"buy.logitechg.com\",\"browserbench.org\",\"flags\",\"www.lttstore.com\",\"dbrand.com\",\"www.boomerangfu.com\",\"www.blackboxmycar.com\",\"www.flexispot.com\",\"moto360.com\",\"www.docker.com\",\"login.nvgs.nvidia.com\",\"www.nvidia.com\",\"chromeunboxed.com\",\"wiki.debian.org\",\"www.vividracing.com\",\"www.insta360.com\",\"en.wikichip.org\",\"www.delta.com\",\"www.steamgriddb.com\",\"www.8bitdo.com\",\"electrameccanica.com\",\"www.automotivetouchup.com\",\"win10.guru\",\"docs.microsoft.com\",\"repl.it\",\"www.neverware.com\",\"www.asrock.com\",\"www.klipnik.com\",\"support.plex.tv\",\"www.elpamsoft.com\",\"www.upliftdesk.com\",\"www.plex.tv\",\"egift.activationspot.com\",\"forum.level1techs.com\",\"imgflip.com\",\"catrain.org\",\"guide.neverware.com\",\"www.autotempest.com\",\"www.facebook.com\",\"en.wikipedia.org\",\"support.google.com\",\"thedroidguy.com\",\"newtab\",\"www.techradar.com\",\"www.pcmag.com\",\"www.codeweavers.com\",\"login.live.com\",\"spelunky.fandom.com\",\"apple.stackexchange.com\",\"components.pwabuilder.com\",\"love2dev.com\",\"theodyssey.dev\",\"www.evga.com\",\"www.twitch.tv\",\"store.asus.com\",\"www.gpowercharger.com\",\"www.anker.com\",\"www.testufo.com\",\"testufo.com\",\"messages.google.com\",\"www.gamersnexus.net\",\"www.sonic.com\",\"support.razer.com\",\"mysupport.razer.com\",\"drivers.razersupport.com\",\"www.virtualbox.org\",\"www.aukey.com\",\"www.3dmark.com\",\"www.fiberopticproducts.com\",\"parsec.app\",\"www.project-aurora.com\",\"www.jetbrains.com\",\"returns.seagate.com\",\"www.walkingpad.com\",\"onewheel.com\",\"www.glasswire.com\",\"accounts.yoyogames.com\",\"www.nowinstock.net\",\"www.porsche.com\",\"cc.porsche.com\",\"www.tirerack.com\",\"reviewtire.com\",\"www.ccleaner.com\",\"www.annepro.net\",\"yawego.com\",\"chocolatey.org\",\"www.google.com\",\"sendfile.su\",\"wiki.unraid.net\",\"www.genkithings.com\",\"www.nanoxiausa.com\",\"kprepublic.com\",\"xboxdesignlab.xbox.com\",\"forza.fandom.com\",\"jdownloader.org\",\"www.kia.com\",\"arstechnica.com\",\"www.amazon.com\",\"epubreader.1bestlink.net\",\"shop.westerndigital.com\",\"www.questmanager.com\",\"speedtest.xfinity.com\",\"buy.spectrum.com\",\"support.xbox.com\",\"www.tesla.com\",\"www.hexcore.xyz\",\"3ds.hacks.guide\",\"switch.homebrew.guide\",\"gg.deals\",\"us.nothing.tech\",\"www.racingbeat.com\",\"secure.newegg.com\",\"www.flyinmiata.com\",\"mkturbo.com\",\"miataroadster.com\",\"corksport.com\",\"mail.google.com\",\"automobiles.honda.com\",\"blog.flipperzero.one\",\"egpu.io\",\"remotedesktop.google.com\",\"gbatemp.net\",\"www.xfinity.com\",\"retrogamecorps.com\",\"ea.arcsivr.com\",\"www.webarcode.com\",\"www.nissanusa.com\",\"www.thezebra.com\",\"voxeltycoon.xyz\",\"www.codecademy.com\",\"192.168.1.25\",\"outervision.com\",\"www.videocardbenchmark.net\",\"www.hyundaicanada.com\",\"www.hyundaiusa.com\",\"www.westerndigital.com\",\"support-en.wd.com\",\"mazdashifters.com\",\"lutris.net\",\"rewards.microsoft.com\",\"www.cyberciti.biz\",\"www.image-line.com\",\"www.vw.com\",\"www.browserstack.com\",\"app-automate.browserstack.com\",\"web.archive.org\",\"trade.aliexpress.com\",\"sia.tech\",\"filecoin.io\",\"wearepapermill.co\",\"k"
siteList_1: "eepersecurity.com\"]"
syncSettings: false
syncSitesFixes: false
theme: {brightness: 100, contrast: 100, darkColorScheme: 'Default', darkSchemeBackgroundColor: '#181a1b', darkSchemeTextColor: '#e8e6e3', …}
time: {activation: '18:00', deactivation: '9:00'}
[[Prototype]]: Object
```
    
chrome.storage.sync.get(null, console.log):

```
chrome.storage.sync.get(null, console.log)
undefined
{applyToListedOnly: false, automation: '', automationBehaviour: 'OnOff', changeBrowserTheme: false, customThemes: Array(0), …}
applyToListedOnly: false
automation: ""
automationBehaviour: "OnOff"
changeBrowserTheme: false
customThemes: []
detectDarkTheme: false
enableContextMenus: false
enableForPDF: false
enableForProtectedPages: false
enabled: true
fetchNews: true
location: {latitude: null, longitude: null}
presets: []
previewNewDesign: false
readNews: (19) ['no-war', 'chrome-favorites-2021', 'thanks-2021', '5m-users', 'v4-9-16', 'v4-9', 'attention', 'dr-5-announcement', '2m-users', 'automation', 'product-hunt-golden-kitty-2018', 'time-settings', 'safari', '500k-users', 'stylish', 'product-hunt', 'custom-site-settings', 'thanks-for-contribution', 'dynamic-theme']
siteList: Array(6)
0: "192.168.1.1"
1: "dbrand.com"
2: "www.logitech.com"
3: "mail.google.com"
4: "shop.flipperzero.one"
5: "mazdashifters.com"
length: 6
[[Prototype]]: Array(0)
siteListEnabled: []
syncSettings: true
syncSitesFixes: false
theme: {brightness: 100, contrast: 100, darkColorScheme: 'Default', darkSchemeBackgroundColor: '#181a1b', darkSchemeTextColor: '#e8e6e3', …}
time: {activation: '18:00', deactivation: '9:00'}
[[Prototype]]: Object
```

**Comment by Gusted** [comment]
Seems like a couple of issues are going on here, would need to take a deeper dive in how this can happen and how to correctly prevent such issue without messing up current settings 😅.

**Comment by sOkeif** [comment]
Just experienced this issue, after a recent chrome update, but I did not locate this issue before removing and re-installing to restore functionality. If this issue occurs again I will capture and share the output from console.

**Comment by techiata** [comment]
@Gusted Is it possible that the `siteList` value in my local storage (`siteList: {__meta_split_count: 2}`)is causing `TypeError: sourceList.slice is not a function` due to it not being the correct data/object type when it gets passed through in the `getToggledList` function and is therefore missing the `slice` function? I'm guessing an array is expected in line 5124, but that's not what it's getting when `{__meta_split_count: 2}` is set as `siteList` due to `siteList` going above the 8Kb limit for chrome.storage.sync.QUOTA_BYTES_PER_ITEM and getting split up into SiteList_0, SiteList_1, etc.

**Comment by techiata** [comment]
I couldn't figure out how to make it happen organically (probably needed to wait for the local/sync storage to sync up), but by using the Storage Area Explorer chrome extension, I was able to modify siteList to contain:
`{
	"__meta_split_count": 2
}`
and  then after disabling and re-enabling the DR extension, I was able to reproduce the sourceList.slice and props.values.map errors.

**Comment by Gusted** [comment]
That shouldn't be possible. We pre-process the settings: https://github.com/darkreader/darkreader/blob/dd96929ea635c94927c43b22a0bd6de5f6cc9bc9/src/background/utils/extension-api.ts#L49-L72

**Comment by techiata** [comment]
Got it, makes sense. When and how often does this sync happen? I'm wondering if something is preventing that pre-processing function(s) from running or running properly and instead of SiteList_0 and SiteList_1 getting merged into one list, `__meta_split_count: 2` is getting returned instead to functions like `getToggledList` when they GET siteList.

**Comment by Gusted** [comment]
> Got it, makes sense. When and how often does this sync happen?

On startup + when it detects that another browser instance(with the same syncing account)  has changed the settings.



> I'm wondering if something is preventing that pre-processing function(s) from running or running properly and instead of SiteList_0 and SiteList_1 getting merged into one list, `__meta_split_count: 2` is getting returned instead to functions like `getToggledList` when they GET siteList.

Yeah the pre-processing is not doing something correctly.. But I'm not able to reproduce it on my machine so far.

**Comment by bartekpacia** [comment]
Same error, insanely irritating.

**Comment by rejetto** [comment]
I had this problem many times, I'm having it right now and it may be or not a coincidence that the website with the problem is using a custom port, so it is specified in the URL.

**Comment by direrFlood** [comment]
https://github.com/darkreader/darkreader/pull/10216
