### ISSUE TITLE
Cannot update from git repo: Cannot find module 'globby'

### ISSUE THREAD

**Issue by marcelpaulo** [darkreader/darkreader#906]
It had been months since I last updated darkreader from the git repo, and when I tried it right now, it failed with these messages:

```
Error: Cannot find module 'globby'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/paulo/src/darkreader/tasks/copy.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module.m._compile (/home/paulo/src/darkreader/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/paulo/src/darkreader/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! darkreader@4.7.1 release: `npm test && node tasks/release.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the darkreader@4.7.1 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/paulo/.npm/_logs/2018-12-12T07_20_04_058Z-debug.log
```

[Here](http://paste.openstack.org/show/737109)'s the debug log.

My environment:

OS: Xubuntu 18.04.1 LTS
nodejs: 10.14.2-1nodesource1

**Comment by alexanderby** [comment]
Some time ago I reworked the build scripts due to and [NPM issue](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident). Many packages were removed from dev dependencies, so you should run `npm install`.

**Comment by marcelpaulo** [comment]
Thank you so much, @alexanderby! I've just built darkreader, after running `npm install`.
