### ISSUE TITLE
Solarized Dark

### ISSUE THREAD

**Issue by dskrad** [darkreader/darkreader#931]
Please add option for solarized dark color scheme.

**Comment by dj8** [comment]
Couldn't agree more! I'd love a way to be able to use the Dynamic generation mode with a Solarized dark colour scheme!

**Comment by dj8** [comment]
Couldn't agree more! I'd love a way to be able to use the Dynamic generation mode with a Solarized dark colour scheme! Perhaps linked in some way to the Dynamic mode color picker (https://github.com/darkreader/darkreader/issues/650).

**Comment by ovigia** [comment]
that would be quite nice.

**Comment by Doonut** [comment]
+1

**Comment by aidanSoles** [comment]
This would be sick. I'm not sure about licensing, but you might be able to reproduce some of the awesome work done here: https://github.com/alphapapa/solarized-everything-css.

**Comment by aherstein** [comment]
I would love this as well. I have severe astigmatism and I find most dark modes to be quite unreadable. Solarized Dark is the only one that doesn't produce a ton of glare for me.

**Comment by omeringen** [comment]
> I would love this as well. I have severe astigmatism and I find most dark modes to be quite unreadable. Solarized Dark is the only one that doesn't produce a ton of glare for me.

I  agree. I also voted for the first post.

**Comment by ashkan-leo** [comment]
This would be a great addition

**Comment by Gusted** [comment]
Darkreader v5 will contain options to change some colors. Like the background.

**Comment by Gusted** [comment]
Hi their!

Their had been some progress from the owner of Dark Reader @alexanderby(All credits to him thank you) Their's now added support to change some colors(If you have a good suggestion make sure to comment it)
 ![](https://i.imgur.com/SQ5R3gd.png) 
Background & Text. So with Solarized background as `#002b36`(Unsure if this the official one) It will become something like this 
![](https://i.imgur.com/j7LsgiB.png)
We will try to implement Pre-Themes so you can set this theme without any hassle.
I just need to have a good list of hex color that should be used.

Regards,
Gusted

**Comment by ovigia** [comment]
next, nord theme ;)

**Comment by Gusted** [comment]
Hello their!

I made a new PR #2876 that add a new Drop-Down so you can select it out of the box! Here is a quick preview of how the Solarized Dark looks like( I also made a Solarized Light for Light mode users ;) ). 

[GIF](https://i.imgur.com/AugfxI5.gifv)

I'm also planned to add more out of the box Color-Schemes like 
> next, nord theme ;)

If any of you have other color schemes as suggestion, please leave them here! So I can add them :)

**Comment by Gusted** [comment]
Hi @ovigia!

![](https://i.imgur.com/sPHZCE5.png)
Not sure if those are the correct colors 😬 But it will look something like this ;)

**Comment by ovigia** [comment]
@Gusted nice, thks....

the colors are here https://www.nordtheme.com/

**Comment by Gusted** [comment]
Found that already.
https://github.com/darkreader/darkreader/blob/9ce88682b503dbac9f662c2ad79c5d703393807d/src/colorScheme.ts#L29 I used that colors

**Comment by danielfalbo** [comment]
Probably a very stupid question, buuutt....how do I change the color scheme in Chrome? Does it only work in firefox maybe? 
![Screenshot 2020-11-18 at 17 35 41](https://user-images.githubusercontent.com/39460524/99558946-8b294a80-29c4-11eb-8ac3-bb9f0340823f.png)
Where is the color scheme option? 😅

**Comment by Gusted** [comment]
> Probably a very stupid question, buuutt....how do I change the color scheme in Chrome? Does it only work in firefox maybe?
> ![Screenshot 2020-11-18 at 17 35 41](https://user-images.githubusercontent.com/39460524/99558946-8b294a80-29c4-11eb-8ac3-bb9f0340823f.png)
> Where is the color scheme option? sweat_smile

To activate the new user interface do the following:

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

Custom background, text and selection colors (under Theme click See all options, Colors).

**Comment by danielfalbo** [comment]
Got it, thank you much! Great chrome extension :)

**Comment by MahdiNazemi** [comment]
> Hello their!
> 
> I made a new PR #2876 that add a new Drop-Down so you can select it out of the box! Here is a quick preview of how the Solarized Dark looks like( I also made a Solarized Light for Light mode users ;) Not previewed here ).
> 
> [GIF](https://i.imgur.com/AugfxI5.gifv)
> 
> I'm also planned to add more out of the box Color-Schemes like
> 
> > next, nord theme ;)
> 
> If any of you have other color schemes as suggestion, please leave them here! So I can add them :)

Is this available for Firefox too? I follow all steps shown in the GIF but do not see a "Color Scheme" option.

**Comment by MahdiNazemi** [comment]
I get the following error when trying to run `npm run debug` on the `Color-Patch` branch.

```
/Users/mahdi/darkreader/node_modules/ts-node/src/index.ts:500
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/ui/popup/theme/controls/color-scheme.tsx:16:17 - error TS2322: Type '{ selected: string; values: string[]; onChange: (v: unknown) => void; }' is not assignable to type 'DropDownProps<unknown>'.
  Property 'values' does not exist on type 'DropDownProps<unknown>'.

16                 values={props.values}
                   ~~~~~~
src/ui/popup/theme/controls/color-scheme.tsx:17:49 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'string'.

17                 onChange={(v) => props.onChange(v)}
                                                   ~

    at createTSError (/Users/mahdi/darkreader/node_modules/ts-node/src/index.ts:500:12)
    at reportTSError (/Users/mahdi/darkreader/node_modules/ts-node/src/index.ts:504:19)
    at getOutput (/Users/mahdi/darkreader/node_modules/ts-node/src/index.ts:739:36)
    at Object.compile (/Users/mahdi/darkreader/node_modules/ts-node/src/index.ts:955:32)
    at Module.m._compile (/Users/mahdi/darkreader/node_modules/ts-node/src/index.ts:1043:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .tsx] (/Users/mahdi/darkreader/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
```

I also tried merging this branch with the current master but get the exact same error.

Can you please share the instructions for building this package or running `npm run build`? I have Node.js v14 installed on macOS 10.15.7.

**Comment by Gusted** [comment]
Hi @MahdiNazemi!

Sorry for the inconvince I've pushed an update to the colors-branch that fixes the mentioned issues. It was such ancient branch that it missed some updates from our UI internals.

**Comment by MahdiNazemi** [comment]
> Hi @MahdiNazemi!
> 
> Sorry for the inconvince I've pushed an update to the colors-branch that fixes the mentioned issues. It was such ancient branch that it missed some updates from our UI internals.

Thank you for updating the branch quickly. I was able to build it successfully.

**Comment by Sada-Mio** [comment]
![darkreader](https://user-images.githubusercontent.com/38301959/115584150-6725aa00-a27f-11eb-95cb-9be315ae2df1.png)

I don't see color schemes, was it removed?

Btw, color picker doesn't work with static mode, is that normal?

**Comment by Gusted** [comment]
> I don't see color schemes, was it removed?

#2876 Still waiting :P

> Btw, color picker doesn't work with static mode, is that normal?

Yup, it's just available for dynamic mode.

**Comment by MahdiNazemi** [comment]
Hi @Gusted Thank you very much for this feature. I've been happily using it since the day you updated it to the new version.

Is there an option to switch between Solarized Light and Solarized Dark automatically based on the system's light/dark mode? Currently, what I do is keep Dark Reader always on and manually toggle between Light and Dark Themes based on the time of the day.

**Comment by Gusted** [comment]
> Is there another branch that supports both these features?

The #2876 does this.

**Comment by MahdiNazemi** [comment]
> > Is there another branch that supports both these features?
> 
> The #2876 does this.

Isn't this the same as the `Color-Patch` branch? I'm currently using that branch but the aforementioned feature does not seem to work on macOS (neither on Firefox nor on Chrome).

**Comment by MahdiNazemi** [comment]
@Gusted There are a few websites where Solarized Dark works as expected but Solarized Light does not. For example, see the screenshot below for how background colors look on Slack:

Solarized Dark
<img width="888" alt="Dark" src="https://user-images.githubusercontent.com/11276349/117345473-6e41e000-ae5b-11eb-8314-064dfe8a0b22.png">

Solarized Light
<img width="888" alt="Light" src="https://user-images.githubusercontent.com/11276349/117345503-77cb4800-ae5b-11eb-8a7b-f268801c906a.png">

Is there an easy fix for this problem?

**Comment by Gusted** [comment]
What you mean? The background-color looks off to you?

**Comment by MahdiNazemi** [comment]
> What you mean? The background-color looks off to you?

I think for Solarized Light, they should look like the following screenshot:
<img width="888" alt="True Light" src="https://user-images.githubusercontent.com/11276349/117487835-757ef180-af20-11eb-9e93-648c4c472046.png">

This is how the background of most websites, including Gmail, is shown when Solarized Light is selected. However, on Slack, the color is different as shown in my previous post.
The Solarized Dark colors are all fine.

**Comment by Gusted** [comment]
You can change it within the popup settings under see all options -> Colors -> background

**Comment by mcarans** [comment]
@Gusted Thanks for your great work on this. I cannot find the option to pick solarized dark. I can only pick dark and light. Is the option coming with the merging of this PR https://github.com/darkreader/darkreader/pull/2876 ?

**Comment by Gusted** [comment]
Ding ding, correct.

**Comment by MahdiNazemi** [comment]
@Gusted It looks like `Color-Patch` can no longer be merged into `master`. Would it be possible to update the branch to address the errors?

**Comment by Gusted** [comment]
Decided to clean up and patch up the code and just thrown it all into the trash can and made sure it's now it's easier to contribute to via the config. See #7110

**Comment by Gusted** [comment]
> @Gusted It'd be cool to see color schemes with light and dark variants automatically switch based on the time of day. For example, automatically use Solarized Light during the day and Solarized Dark at night.

#2102 also a good PR to throw in the trash can and make a much cooler iteration of it.

**Comment by iambeingtracked** [comment]
I may be necroposting, but I would like to see everforest dark hard being added. See: https://github.com/sainnhe/everforest
